In [1]:
import ipynb.fs.full.Funciones as F

# Análisis de Circuitos

### 1) Calcular el Voltaje "Vx" y la potencia consumida por la resistencia R2

<img src='img/eje1.png'>

In [2]:
R1=2
R2=1
R3=3
R4=4
R5=6
R6=1.2
R7=8
R8=12

I=6

In [3]:
Req=F.Paralelo(F.Serie(F.Paralelo(R7,R8),R6),F.Serie(R4,F.Paralelo(R3,R5)))
Rdiv=F.Serie(Req,R2)
IRdiv=F.DivisionCorriente(Rdiv,R1,I)
Vx=F.Ohm(R=R2,I=IRdiv)
Px=F.Potencia(V=Vx,R=R2)

print('El voltaje Vx en la Resistencia 2 es: '+str(round(Vx,2)))
print('La potencia de consumo de la Resistencia 2 es: '+str(round(Px,2)))

El voltaje Vx en la Resistencia 2 es: 2.0
La potencia de consumo de la Resistencia 2 es: 4.0


### 2) Calcular los Voltajes V1, V2 y V3

<img src='img/eje2.png'>

In [4]:
R1=14
R2=15
R3=10

V=40

In [5]:
Req=F.Paralelo(R2,R3)
V2=F.DivisionVoltaje(Req,R1,V)
V3=V2
V1=V-V2

print('Los Voltajes V1, V2 y V3 son: {} V, {} V, {} V'.format(str(round(V1,2)),str(round(V2,2)),str(round(V2,2))))

Los Voltajes V1, V2 y V3 son: 28.0 V, 12.0 V, 12.0 V


### 3) Calcular Voltaje, Corriente y Potencia de la Resistencia de 20k

<img src='img/eje3.png'>

In [6]:
Vo=F.Ohm(I=5e-3,R=10e3)
Idep=F.FDependiente(k=0.01,F=Vo)
Idiv=F.DivisionCorriente(20e3,5e3,Idep)
Vdiv=F.Ohm(R=20e3,I=Idiv)
Pdiv=F.Potencia(I=Idiv,V=Vdiv)

print('Voltaje de la Resistencia de 20k: '+str(round(Vdiv,2))+' V')
print('Corriente de la Resistencia de 20k: '+str(round(Idiv,2))+' A')
print('Potencia de la Resistencia de 20k: '+str(round(Pdiv,2))+' W')

Voltaje de la Resistencia de 20k: 2000.0 V
Corriente de la Resistencia de 20k: 0.1 A
Potencia de la Resistencia de 20k: 200.0 W


### 4) Calcular las corrientes de Malla del Siguiente Circuito

<img src='img/eje5.png'>

In [9]:
I=['i1','i2','i3','i4']
R={'R1':2,'R2':3,'R3':6,'R4':1,'R5':4,'R6':8}
M={1:{'V':30,'R':['R1','R2']},2:{'V':0,'R':['R2','R3','R4']},
   3:{'V':0,'R':['R1','R5']},4:{'V':0,'R':['R3','R6']}}
SM={True:{'I':4,'M':{3:-1,4:1}}}
resultados,R,i=F.Mallas(I,R,M,SM)
print('La Malla Representada por el Arreglo de Resistencias: ')
print(R)
print('El Arreglo de Entradas: \n'+str(i.T))
print('Da como resultado: \n'+str(resultados))

La Malla Representada por el Arreglo de Resistencias: 
[[ 5 -3 -2  0]
 [-3 10  0 -6]
 [-2 -6  6 14]
 [ 0  0 -1  1]]
El Arreglo de Entradas: 
[[30]
 [ 0]
 [ 0]
 [ 4]]
Da como resultado: 
{'i1': 8.561, 'i2': 4.636, 'i3': -0.553, 'i4': 3.447}


### 5) Calcular las corrientes de Malla del Siguiente Circuito

<img src='img/eje6.png'>

In [5]:
#Vo=3*i1   >>>   la fuente de voltaje es entonces: 2*3*i1=6*i1 y eso se tomara como carga (R)

I=['i1','i2']
R={'R1':3,'R2':8,'R3':6,'F1':{'D':1,'k':6}}   #k: Ganancia (Se coloca positiva por el sentido de la corriente)
                                            #D: Dependencia con 'N' Malla
M={1:{'V':12,'R':['R1','R2']},2:{'V':0,'R':['R2','R3'],'D':['F1']}}

resultados,R,i=F.Mallas(I,R,M,SM=False,FD=True)

print('La Malla Representada por el Arreglo de Resistencias: ')
print(R)
print('El Arreglo de Entradas: \n'+str(i.T))
print('Da como resultado: \n'+str(resultados))

La Malla Representada por el Arreglo de Resistencias: 
[[11 -8]
 [-2 14]]
El Arreglo de Entradas: 
[[12]
 [ 0]]
Da como resultado: 
{'i1': 1.217, 'i2': 0.174}


### 6) Calcular las voltajes del Siguiente Circuito utilizando LVK

<img src='img/eje2.png'>

In [15]:
I=['i1','i2']
R={'R1':14,'R2':15,'R3':10}
M={1:{'V':40,'R':['R1','R2']},2:{'V':0,'R':['R2','R3']}}

I,MR,inp=F.Mallas(I,R,M)
V1=I['i1']*R['R1']
V2=R['R2']*(I['i1']-I['i2'])
V3=I['i2']*R['R3']

print('v1: '+str(V1))
print('v2: '+str(V2))
print('v3: '+str(V3))

v1: 28.0
v2: 12.0
v3: 12.0


### 7) Calcular el Voltaje de Thevenin y Resistencia de Thevenin entre Terminales "a" y "b"

<img src='img/eje4.png'>

#### Voltaje de Thevenin

In [7]:
Vf=40
If=3

R1=10
R2=40
R3=20

VR3=F.Ohm(I=If,R=R3)
VR2=F.DivisionVoltaje(R2,R1,Vf)

Vth=VR2+VR3
print('Voltaje de Thevenin = '+str(Vth)+' V')

Voltaje de Thevenin = 92.0 V


#### Resistencia de Thevenin

In [8]:
#Cortocircuito en Vf y Circuito Abierto en If

Rth=F.Serie(F.Paralelo(R1,R2),R3)
print('Resistencia de Thevenin = '+str(Rth)+ ' Ohm')

Resistencia de Thevenin = 28.0 Ohm
